# Generated by Django 5.1.7 on 2025-04-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='goal',
        ),
    ]
