# Generated by Django 5.1.7 on 2025-04-21 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0002_remove_trainee_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('treadmill_elevation', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('calories_burned', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trainees.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='CalorieLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('calories_burned', models.FloatField()),
                ('calories_consumed', models.FloatField()),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainees.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainees.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_minutes', models.PositiveIntegerField(default=150)),
                ('target_calories', models.FloatField(default=2000)),
                ('target_weight', models.FloatField(blank=True, null=True)),
                ('trainee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trainees.trainee')),
            ],
        ),
    ]
