# Generated by Django 5.1.7 on 2025-04-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainer_goal_points_trainer_points_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightlog',
            name='trainee',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='WeightLog',
        ),
    ]
